<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EmployeeDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // $employee = [
        //     [
        //         'name' => 'Chf Tech Muhammad Shabbir Ahmed (Retd)',
        //         'father_name' => 'Muhammad Shareef Pervaiz',
        //         'designation' => 'Asst Accountant',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => '476637',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '2019-01-11',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0322-3221520',
        //         'cnic_no' => '35201-1341255-5',
        //         'address' => 'House No 14-A Street 47 Mujahida Bad Mughalpura Lahore Cantt',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],
        //     [
        //         'name' => 'Cwo Noor Muhammad (Retd)',
        //         'father_name' => 'Fazal Hussain',
        //         'designation' => 'Security Incharge',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => '482907',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '2021-01-03',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0320-9059801',
        //         'cnic_no' => '37105-0244573-5',
        //         'address' => 'Village And Post Office Maira Sharif Teh Pindi Ghebe Distt Attock',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],
        //     [
        //         'name' => 'Cwo Munawar Kamboh (Retd)',
        //         'father_name' => 'Jalal Din',
        //         'designation' => 'Office Manager',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => '483838',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '2023-01-01',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0321-4383508',
        //         'cnic_no' => '36102-2958137-1',
        //         'address' => '',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],
        //     [
        //         'name' => 'Shaukat Ali',
        //         'father_name' => 'Nazer Hussain',
        //         'designation' => 'Accounts Manager',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => '486674',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '16/03/2023',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0344-4289025',
        //         'cnic_no' => '34501-1954309-3',
        //         'address' => 'Village Borhi Wali Teh & Dist Narowal',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],
        //     [
        //         'name' => 'Khalil Ahmad',
        //         'father_name' => 'Muhammad Yasin',
        //         'designation' => 'Store Incharge',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => '487030',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '15/02/2021',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0300-6937019',
        //         'cnic_no' => '36502-1241252-3',
        //         'address' => 'House No 52-B Gulshan Park Near Ali View Park Lahore Cantt',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],
        //     [
        //         'name' => 'Cpl/T Muhammad Adnan',
        //         'father_name' => 'Muhammad Ramzan',
        //         'designation' => 'Supervisor',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => '510588',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0303-8642651',
        //         'cnic_no' => '35403-6163398-1',
        //         'address' => 'House No-8 Stareet-4 Hassan Park Teh & Distt Sheikhupura',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],
        //     [
        //         'name' => 'Nsr Tech Wajahat Ali',
        //         'father_name' => 'Amjad Ali',
        //         'designation' => 'Supervisor',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => '522462',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '29/05/2019',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0303-8700921',
        //         'cnic_no' => '35202-4460904-7',
        //         'address' => 'House No E-130 Ali View Park Lahore Cantt',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],
        //     [
        //         'name' => 'Amjad Ali',
        //         'father_name' => 'Sardar Khan',
        //         'designation' => 'Golf Manager',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => 'T-31314',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0300-4980909',
        //         'cnic_no' => '35202-2511345-9',
        //         'address' => 'House No E-130 Ali View Park Lahore Cantt',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],

        //     [
        //         'name' => 'Azam Sadiq Mashi',
        //         'father_name' => 'Sadiq Mashi',
        //         'designation' => 'Security Guard',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => 'ZB-32786',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '2016-01-01',
        //         'date_of_birth' => '',
        //         'religion' => 'Christian',
        //         'phone' => '0322-4606186',
        //         'cnic_no' => '35201-7400830-3',
        //         'address' => '',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],

        //     [
        //         'name' => 'Imran Saqib',
        //         'father_name' => 'Maqsood Ahmed',
        //         'designation' => 'Security Guard',
        //         'employee_type' => 'ARMED FORCES',
        //         'service_no' => 'ZB-48559',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0303-4723560',
        //         'cnic_no' => '34501-1917452-5',
        //         'address' => 'Ghazi Wal Colony, Ghazi Wal, Post Narowal Teh & Distt Narowal',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],

        //     [
        //         'name' => 'M Waseem',
        //         'father_name' => 'Ali Ahmed',
        //         'designation' => 'Lascer',
        //         'employee_type' => 'CIVIL',
        //         'service_no' => 'ZB-51961',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '2019-03-08',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0304-5537161',
        //         'cnic_no' => '35201-4283398-7',
        //         'address' => '195-X Phase-III DHA Lahore',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],

        //     [
        //         'name' => 'Amir Shahzad',
        //         'father_name' => 'Muhammad Shabbir',
        //         'designation' => 'Lascer',
        //         'employee_type' => 'CIVIL',
        //         'service_no' => 'ZB-51963',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0344-1045654',
        //         'cnic_no' => '35201-1546485-9',
        //         'address' => 'Eno Bhatti Dhakkhana Bhbanpurra Lahore',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],

        //     [
        //         'name' => 'Muhammad Majid Ali',
        //         'father_name' => 'Muhammad Sharif',
        //         'designation' => 'Lascer',
        //         'employee_type' => 'CIVIL',
        //         'service_no' => 'ZB-51963',
        //         'job_type' => 'Permanent',
        //         'joining_date' => '',
        //         'date_of_birth' => '',
        //         'religion' => 'Islam',
        //         'phone' => '0305-4170634',
        //         'cnic_no' => '35201-8986600-5',
        //         'address' => 'House no A-175 Gali No 16 Muhallah Shuttar Sadar Bazar Lahore Cantt',
        //         'department' => '',
        //         'section' => '',
        //         'gender' => '',
        //         'marital_status' => '',
        //         'blood_group' => '',
        //         'nationality' => '',
        //         'domicile' => '',
        //         'qualification' => '',
        //         'current_salary' => '',
        //     ],

        // ];

    }
}
