<?php

namespace Database\Seeders;

use App\Models\Room;
use Illuminate\Database\Seeder;

class Rooms extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rooms = [
            [
                'room_title' => 'Room C-1',
                'is_reserved' => 1,
                'category_id' => 2,
                'block' => 'C-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room C-2',
                'is_reserved' => 1,
                'category_id' => 2,
                'block' => 'C-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room C-3',
                'is_reserved' => 1,
                'category_id' => 1,
                'block' => 'C-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room C-4',
                'is_reserved' => 1,
                'category_id' => 1,
                'block' => 'C-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room C-5',
                'is_reserved' => 1,
                'category_id' => 1,
                'block' => 'C-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room C-6',
                'is_reserved' => 1,
                'category_id' => 1,
                'block' => 'C-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            // B Block Rooms
            [
                'room_title' => 'Room A-208',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'B-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-209',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'B-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-210',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'B-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-211',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'B-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-212',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'B-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-213',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'B-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-214',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'B-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-215',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'B-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            // A Block Rooms
            [
                'room_title' => 'Room A-102',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-103',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-104',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-105',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-106',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-107',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-108',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-109',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-110',
                'is_reserved' => 0,
                'category_id' => 1,
                'block' => 'A-Block',
                'floor' => 'Ground',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 5000,
                'member_guest' => 9000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-201',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'A-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-202',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'A-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-203',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'A-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-204',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'A-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-205',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'A-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-206',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'A-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
            [
                'room_title' => 'Room A-207',
                'is_reserved' => 0,
                'category_id' => 2,
                'block' => 'A-Block',
                'floor' => 'First',
                'single_person_charges' => 0,
                'double_person_charges' => 0,
                'member_self' => 8000,
                'member_guest' => 12000,
                'tenant_id' => 'pcom',
            ],
        ];

        Room::insert($rooms);
    }
}
